var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,g){a!=Array.prototype&&a!=Object.prototype&&(a[b]=g.value)};
$jscomp.polyfill=function(a,b,g,f){if(b){g=$jscomp.global;a=a.split(".");for(f=0;f<a.length-1;f++){var d=a[f];d in g||(g[d]={});g=g[d]}a=a[a.length-1];f=g[a];b=b(f);b!=f&&null!=b&&$jscomp.defineProperty(g,a,{configurable:!0,writable:!0,value:b})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function g(c){return c instanceof d?c:new d(function(b,a){b(c)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;b.prototype.asyncExecute=function(c){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(c);return this};b.prototype.asyncExecuteBatch_=function(){var c=this;this.asyncExecuteFunction(function(){c.executeBatch_()})};var f=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(c){f(c,
0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var c=this.batch_;this.batch_=[];for(var b=0;b<c.length;++b){var a=c[b];c[b]=null;try{a()}catch(w){this.asyncThrow_(w)}}}this.batch_=null};b.prototype.asyncThrow_=function(c){this.asyncExecuteFunction(function(){throw c;})};var d=function(c){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{c(b.resolve,b.reject)}catch(m){b.reject(m)}};d.prototype.createResolveAndReject_=
function(){function c(c){return function(d){a||(a=!0,c.call(b,d))}}var b=this,a=!1;return{resolve:c(this.resolveTo_),reject:c(this.reject_)}};d.prototype.resolveTo_=function(c){if(c===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(c instanceof d)this.settleSameAsPromise_(c);else{a:switch(typeof c){case "object":var b=null!=c;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(c):this.fulfill_(c)}};d.prototype.resolveToNonPromiseObj_=function(c){var b=
void 0;try{b=c.then}catch(m){this.reject_(m);return}"function"==typeof b?this.settleSameAsThenable_(b,c):this.fulfill_(c)};d.prototype.reject_=function(b){this.settle_(2,b)};d.prototype.fulfill_=function(b){this.settle_(1,b)};d.prototype.settle_=function(b,a){if(0!=this.state_)throw Error("Cannot settle("+b+", "+a+"): Promise already settled in state"+this.state_);this.state_=b;this.result_=a;this.executeOnSettledCallbacks_()};d.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var b=
0;b<this.onSettledCallbacks_.length;++b)h.asyncExecute(this.onSettledCallbacks_[b]);this.onSettledCallbacks_=null}};var h=new b;d.prototype.settleSameAsPromise_=function(b){var a=this.createResolveAndReject_();b.callWhenSettled_(a.resolve,a.reject)};d.prototype.settleSameAsThenable_=function(b,a){var c=this.createResolveAndReject_();try{b.call(a,c.resolve,c.reject)}catch(w){c.reject(w)}};d.prototype.then=function(b,a){function c(b,a){return"function"==typeof b?function(a){try{g(b(a))}catch(x){f(x)}}:
a}var g,f,h=new d(function(b,a){g=b;f=a});this.callWhenSettled_(c(b,g),c(a,f));return h};d.prototype.catch=function(b){return this.then(void 0,b)};d.prototype.callWhenSettled_=function(b,a){function c(){switch(d.state_){case 1:b(d.result_);break;case 2:a(d.result_);break;default:throw Error("Unexpected state: "+d.state_);}}var d=this;null==this.onSettledCallbacks_?h.asyncExecute(c):this.onSettledCallbacks_.push(c)};d.resolve=g;d.reject=function(b){return new d(function(a,c){c(b)})};d.race=function(b){return new d(function(a,
c){for(var d=$jscomp.makeIterator(b),f=d.next();!f.done;f=d.next())g(f.value).callWhenSettled_(a,c)})};d.all=function(b){var a=$jscomp.makeIterator(b),c=a.next();return c.done?g([]):new d(function(b,d){function f(a){return function(c){h[a]=c;m--;0==m&&b(h)}}var h=[],m=0;do h.push(void 0),m++,g(c.value).callWhenSettled_(f(h.length-1),d),c=a.next();while(!c.done)})};return d},"es6","es3");
$jscomp.findInternal=function(a,b,g){a instanceof String&&(a=String(a));for(var f=a.length,d=0;d<f;d++){var h=a[d];if(b.call(g,h,d,a))return{i:d,v:h}}return{i:-1,v:void 0}};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(b,a){return $jscomp.findInternal(this,b,a).v}},"es6","es3");
function _typeof(a){_typeof="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(b){return typeof b}:function(b){return b&&"function"===typeof Symbol&&b.constructor===Symbol&&b!==Symbol.prototype?"symbol":typeof b};return _typeof(a)}var _regenerator;
(function(){var a=function(b){function a(b,l,a,c){l=Object.create((l&&l.prototype instanceof d?l:d).prototype);c=new C(c||[]);l._invoke=w(b,a,c);return l}function f(b,l,a){try{return{type:"normal",arg:b.call(l,a)}}catch(K){return{type:"throw",arg:K}}}function d(){}function h(){}function c(){}function E(b){["next","throw","return"].forEach(function(l){b[l]=function(b){return this._invoke(l,b)}})}function m(b,l){function a(e,c,q,d){e=f(b[e],b,c);if("throw"===e.type)d(e.arg);else{var k=e.arg;return(e=
k.value)&&"object"===_typeof(e)&&r.call(e,"__await")?l.resolve(e.__await).then(function(b){a("next",b,q,d)},function(b){a("throw",b,q,d)}):l.resolve(e).then(function(b){k.value=b;q(k)},function(b){return a("throw",b,q,d)})}}var e;this._invoke=function(b,q){function c(){return new l(function(e,l){a(b,q,e,l)})}return e=e?e.then(c,c):c()}}function w(b,l,a){var e=G;return function(c,d){if(e===H)throw Error("Generator is already running");if(e===y){if("throw"===c)throw d;return x()}a.method=c;for(a.arg=
d;;){if(c=a.delegate)if(c=F(c,a)){if(c===n)continue;return c}if("next"===a.method)a.sent=a._sent=a.arg;else if("throw"===a.method){if(e===G)throw e=y,a.arg;a.dispatchException(a.arg)}else"return"===a.method&&a.abrupt("return",a.arg);e=H;c=f(b,l,a);if("normal"===c.type){e=a.done?y:L;if(c.arg===n)continue;return{value:c.arg,done:a.done}}"throw"===c.type&&(e=y,a.method="throw",a.arg=c.arg)}}}function F(b,a){var e=b.iterator[a.method];if(e===p){a.delegate=null;if("throw"===a.method){if(b.iterator["return"]&&
(a.method="return",a.arg=p,F(b,a),"throw"===a.method))return n;a.method="throw";a.arg=new TypeError("The iterator does not provide a 'throw' method")}return n}e=f(e,b.iterator,a.arg);if("throw"===e.type)return a.method="throw",a.arg=e.arg,a.delegate=null,n;e=e.arg;if(!e)return a.method="throw",a.arg=new TypeError("iterator result is not an object"),a.delegate=null,n;if(e.done)a[b.resultName]=e.value,a.next=b.nextLoc,"return"!==a.method&&(a.method="next",a.arg=p);else return e;a.delegate=null;return n}
function J(a){var b={tryLoc:a[0]};1 in a&&(b.catchLoc=a[1]);2 in a&&(b.finallyLoc=a[2],b.afterLoc=a[3]);this.tryEntries.push(b)}function B(a){var b=a.completion||{};b.type="normal";delete b.arg;a.completion=b}function C(a){this.tryEntries=[{tryLoc:"root"}];a.forEach(J,this);this.reset(!0)}function D(a){if(a){var b=a[z];if(b)return b.call(a);if("function"===typeof a.next)return a;if(!isNaN(a.length)){var e=-1;b=function k(){for(;++e<a.length;)if(r.call(a,e))return k.value=a[e],k.done=!1,k;k.value=
p;k.done=!0;return k};return b.next=b}}return{next:x}}function x(){return{value:p,done:!0}}var I=Object.prototype,r=I.hasOwnProperty,p,t="function"===typeof Symbol?Symbol:{},z=t.iterator||"@@iterator",M=t.asyncIterator||"@@asyncIterator",A=t.toStringTag||"@@toStringTag";b.wrap=a;var G="suspendedStart",L="suspendedYield",H="executing",y="completed",n={};t={};t[z]=function(){return this};var u=Object.getPrototypeOf;(u=u&&u(u(D([]))))&&u!==I&&r.call(u,z)&&(t=u);var v=c.prototype=d.prototype=Object.create(t);
h.prototype=v.constructor=c;c.constructor=h;c[A]=h.displayName="GeneratorFunction";b.isGeneratorFunction=function(a){return(a="function"===typeof a&&a.constructor)?a===h||"GeneratorFunction"===(a.displayName||a.name):!1};b.mark=function(a){Object.setPrototypeOf?Object.setPrototypeOf(a,c):(a.__proto__=c,A in a||(a[A]="GeneratorFunction"));a.prototype=Object.create(v);return a};b.awrap=function(a){return{__await:a}};E(m.prototype);m.prototype[M]=function(){return this};b.AsyncIterator=m;b.async=function(c,
d,q,f,k){void 0===k&&(k=Promise);var e=new m(a(c,d,q,f),k);return b.isGeneratorFunction(d)?e:e.next().then(function(a){return a.done?a.value:e.next()})};E(v);v[A]="Generator";v[z]=function(){return this};v.toString=function(){return"[object Generator]"};b.keys=function(a){var b=[],c;for(c in a)b.push(c);b.reverse();return function k(){for(;b.length;){var c=b.pop();if(c in a)return k.value=c,k.done=!1,k}k.done=!0;return k}};b.values=D;C.prototype={constructor:C,reset:function(a){this.next=this.prev=
0;this.sent=this._sent=p;this.done=!1;this.delegate=null;this.method="next";this.arg=p;this.tryEntries.forEach(B);if(!a)for(var b in this)"t"===b.charAt(0)&&r.call(this,b)&&!isNaN(+b.slice(1))&&(this[b]=p)},stop:function(){this.done=!0;var a=this.tryEntries[0].completion;if("throw"===a.type)throw a.arg;return this.rval},dispatchException:function(a){function b(b,d){f.type="throw";f.arg=a;c.next=b;d&&(c.method="next",c.arg=p);return!!d}if(this.done)throw a;for(var c=this,e=this.tryEntries.length-1;0<=
e;--e){var d=this.tryEntries[e],f=d.completion;if("root"===d.tryLoc)return b("end");if(d.tryLoc<=this.prev){var g=r.call(d,"catchLoc"),h=r.call(d,"finallyLoc");if(g&&h){if(this.prev<d.catchLoc)return b(d.catchLoc,!0);if(this.prev<d.finallyLoc)return b(d.finallyLoc)}else if(g){if(this.prev<d.catchLoc)return b(d.catchLoc,!0)}else if(h){if(this.prev<d.finallyLoc)return b(d.finallyLoc)}else throw Error("try statement without catch or finally");}}},abrupt:function(a,b){for(var c=this.tryEntries.length-
1;0<=c;--c){var d=this.tryEntries[c];if(d.tryLoc<=this.prev&&r.call(d,"finallyLoc")&&this.prev<d.finallyLoc){var e=d;break}}e&&("break"===a||"continue"===a)&&e.tryLoc<=b&&b<=e.finallyLoc&&(e=null);c=e?e.completion:{};c.type=a;c.arg=b;return e?(this.method="next",this.next=e.finallyLoc,n):this.complete(c)},complete:function(a,b){if("throw"===a.type)throw a.arg;"break"===a.type||"continue"===a.type?this.next=a.arg:"return"===a.type?(this.rval=this.arg=a.arg,this.method="return",this.next="end"):"normal"===
a.type&&b&&(this.next=b);return n},finish:function(a){for(var b=this.tryEntries.length-1;0<=b;--b){var c=this.tryEntries[b];if(c.finallyLoc===a)return this.complete(c.completion,c.afterLoc),B(c),n}},"catch":function(a){for(var b=this.tryEntries.length-1;0<=b;--b){var c=this.tryEntries[b];if(c.tryLoc===a){a=c.completion;if("throw"===a.type){var d=a.arg;B(c)}return d}}throw Error("illegal catch attempt");},delegateYield:function(a,b,c){this.delegate={iterator:D(a),resultName:b,nextLoc:c};"next"===this.method&&
(this.arg=p);return n}};return b}("object"===("undefined"===typeof module?"undefined":_typeof(module))?module.exports:{});try{_regenerator=a}catch(b){Function("r","_regenerator = r")(a)}})();
(function(){seraph_dlstat.Settings={_int:{StrItem_OnAdd:function(a){function b(a){(a=a.trim())&&seraph_dlstat.Ui.TokensList.AddItem(d[0],a)}var g=1<arguments.length&&void 0!==arguments[1]?arguments[1]:",",f=jQuery(a.parentNode).closest(".block").first(),d=f.find(".vals");f=f.find(".val");g?f.val().split(g).forEach(b):b(f.val());f.val("")}}}})();
