var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,c,b){a instanceof String&&(a=String(a));for(var d=a.length,e=0;e<d;e++){var f=a[e];if(c.call(b,f,e,a))return{i:e,v:f}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,b){a!=Array.prototype&&a!=Object.prototype&&(a[c]=b.value)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(a,c,b,d){if(c){b=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in b||(b[e]={});b=b[e]}a=a[a.length-1];d=b[a];c=c(d);c!=d&&null!=c&&$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:c})}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,b){return $jscomp.findInternal(this,a,b).v}},"es6","es3");window.seraph_dlstat||(window.seraph_dlstat={});
(function(){seraph_dlstat.PluginAdmin={AdvertProductsContentInit:function(a,c,b,d,e,f){function l(a,b){var c="";var e=a.images;if(Array.isArray(e)){for(var f=-1,l=2147483647,m=-1,h=2147483647,k=0;k<e.length;k++){var g=e[k];if(b==g.width){f=k;break}b<g.width?(g=g.width-b,g<l&&(f=k,l=g)):(g=b-g.width,g<h&&(m=k,h=g))}e=-1!=f?e[f].url:-1!=m?e[m].url:null}else e=null;e&&(c+=seraph_dlstat.Ui.Tag("td",seraph_dlstat.Ui.Link(seraph_dlstat.Ui.Tag("img",null,{"class":"ctlSpaceAfter",width:b,src:e},!0),a.urlInfo,
!0),{style:{width:"1px"}}));c+=seraph_dlstat.Ui.TagOpen("td");c+=seraph_dlstat.Ui.Tag("h3",a.title,{"class":"ctlSpaceVAfter",style:{"margin-top":0}});c+=seraph_dlstat.Ui.Tag("div",a.descr);a.urlInfo&&(c+=seraph_dlstat.Ui.Button(d,!0,null,"ctlSpaceVBefore","button",{onclick:"window.open( '"+a.urlInfo+"', '_blank' )"}));c+=seraph_dlstat.Ui.TagClose("td");return seraph_dlstat.Ui.Tag("table",seraph_dlstat.Ui.Tag("tbody",seraph_dlstat.Ui.Tag("row",c)))}function h(b,c){var d="";if(Array.isArray(b)&&b.length){d+=
seraph_dlstat.Ui.TagOpen("tr");for(var f=0;f<b.length;f++){var h=b[f];0<f&&0==f%e&&(d+=seraph_dlstat.Ui.TagClose("tr")+seraph_dlstat.Ui.TagOpen("tr"));d+=seraph_dlstat.Ui.Tag("td",seraph_dlstat.Ui.Tag("div",l(h,c),{style:{margin:"1em 1em 2em 1em"}}),{"class":"cx-lg-6 cx-xs-12",style:{"vertical-align":"top"}})}for(;f%e;f++)d+=seraph_dlstat.Ui.Tag("td",null,{"class":"cx-lg-6 cx-xs-12"});d+=seraph_dlstat.Ui.TagClose("tr");d=seraph_dlstat.Ui.Tag("table",seraph_dlstat.Ui.Tag("tbody",d))}jQuery(a).html(d)}
jQuery.ajax({url:seraph_dlstat.Net.UpdateQueryArgs(c+"/v1/advert_products",{slug:"downloads-stats",locale:b}),type:"GET",dataType:"json"}).then(function(a){h(a,f)},function(a){h(null,0)})},SwitchTo:function(a,c,b){function d(a,c){e.hide();f.prop("disabled",!1);a&&window.open(b,"_blank").focus()}a=jQuery(".seraph_dlstat_switchto");var e=a.find(".seraph_dlstat_spinner"),f=a.find('input[type="button"]:not(.cancel)');e.show();f.prop("disabled",!0);jQuery.ajax({url:c,type:"post"}).then(function(a){d(!0)},
function(a){d(!1,"OK"===a.statusText?"PHP error: "+a.responseText:"Backend error: "+a.status+" "+a.statusText)})},RateItCont_Set:function(a,c,b){var d=jQuery("#"+a),e=d.find(".actions"),f=d.find(".seraph_dlstat_spinner");e.hide();f.show();jQuery.ajax({url:b+"="+(c?"rateItPostpone":"rateItDisable"),type:"post"}).then(function(a){d.hide()},function(a){e.show();f.hide()})},RateIt_Set:function(a,c){jQuery("#seraph_dlstat_RateIt_Message .actions").hide();jQuery("#seraph_dlstat_RateIt_Message .seraph_dlstat_spinner").show();
jQuery.ajax({url:c+"="+(a?"rateItPostpone":"rateItDisable"),type:"post"}).then(function(a){seraph_dlstat.Ui.BannerMsgClose(jQuery("#seraph_dlstat_RateIt_Message"))},function(a){jQuery("#seraph_dlstat_RateIt_Message .actions").show();jQuery("#seraph_dlstat_RateIt_Message .spinner").hide()})},ChangeVersion_Confirm:function(a){jQuery("#seraph_dlstat_ChangeVersion_Msg .actions").hide();jQuery("#seraph_dlstat_ChangeVersion_Msg .seraph_dlstat_spinner").show();jQuery.ajax({url:a+"=changeVersionConfirm",
type:"post"}).then(function(a){seraph_dlstat.Ui.BannerMsgClose(jQuery("#seraph_dlstat_ChangeVersion_Msg"))},function(a){jQuery("#seraph_dlstat_ChangeVersion_Msg .actions").show();jQuery("#seraph_dlstat_ChangeVersion_Msg .spinner").hide()})},SettImport:function(a,c,b){function d(){f.prop("disabled",!1);e.hide()}if(b){a=jQuery(a.parentNode);var e=a.find(".seraph_dlstat_spinner"),f=a.find("input.button");f.prop("disabled",!0);e.show();a=new FileReader;a.onabort=function(a){d()};a.onerror=function(a){d()};
a.onload=function(a){jQuery.ajax({url:c+"=settImport",type:"post",contentType:"application/json",data:a.target.result}).then(function(){location.reload()},function(a){d()})};a.readAsText(b)}},SettExport:function(a,c){function b(a){a&&window.saveAs(new Blob([a],{type:"text/json"}),"seraphinite-downloads-stats-settings.json");e.prop("disabled",!1);d.hide()}a=jQuery(a.parentNode);var d=a.find(".seraph_dlstat_spinner"),e=a.find("input.button");e.prop("disabled",!0);d.show();jQuery.ajax({url:c+"=settExport",
type:"post"}).then(function(a){seraph_dlstat.Ui.ScriptLoad(document,"https://cdn.jsdelivr.net/npm/file-saver@2.0.5/dist/FileSaver.min.js","file-saver").then(function(){b(a)},function(a){b()})},function(a){b()})},OnSettWizNext:function(a,c){var b=jQuery(a).closest("form");a=jQuery(a.parentNode);var d=b.find(".wizPages");b=d.find(">.active").first();b.get(0)?(c=c?b.next():b.prev(),c.get(0)&&(b.removeClass("active"),b=c)):b=d.children().first();b.addClass("active");c=!!b.next().get(0);b=!!b.prev().get(0);
a.find("input.next").prop("disabled",!c);a.find("input.prev").prop("disabled",!b);c?a.find("input.finish").hide():a.find("input.finish").show()}}})();
